<?php


/**
 * This class defines the structure of the 'dimension' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/15/14 20:44:19
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DimensionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DimensionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('dimension');
		$this->setPhpName('Dimension');
		$this->setClassname('Dimension');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('DIM_CODIGO', 'DimCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('DIM_NOMBRE', 'DimNombre', 'VARCHAR', false, 200, null);
		$this->addColumn('DIM_ELIMINADO', 'DimEliminado', 'SMALLINT', false, 6, null);
		$this->addColumn('DIM_FECHA_REGISTRO_SISTEMA', 'DimFechaRegistroSistema', 'TIMESTAMP', false, null, null);
		$this->addColumn('DIM_USU_CREA', 'DimUsuCrea', 'INTEGER', false, 11, null);
		$this->addColumn('DIM_FECHA_ACTUALIZACION', 'DimFechaActualizacion', 'TIMESTAMP', false, null, null);
		$this->addColumn('DIM_USU_ACTUALIZA', 'DimUsuActualiza', 'INTEGER', false, 11, null);
		$this->addColumn('DIM_CAUSA_ELIMINACION', 'DimCausaEliminacion', 'VARCHAR', false, 250, null);
		$this->addColumn('DIM_CAUSA_ACTUALIZACION', 'DimCausaActualizacion', 'VARCHAR', false, 250, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // DimensionTableMap
