<?php


/**
 * This class defines the structure of the 'grupo_equipo' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/29/14 02:06:09
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class GrupoEquipoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.GrupoEquipoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('grupo_equipo');
		$this->setPhpName('GrupoEquipo');
		$this->setClassname('GrupoEquipo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('GRU_CODIGO', 'GruCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('GRU_NOMBRE', 'GruNombre', 'VARCHAR', false, 200, null);
		$this->addColumn('GRU_FECHA_REGISTRO_SISTEMA', 'GruFechaRegistroSistema', 'TIMESTAMP', false, null, null);
		$this->addColumn('GRU_USU_CREA', 'GruUsuCrea', 'INTEGER', false, 11, null);
		$this->addColumn('GRU_USU_ACTUALIZA', 'GruUsuActualiza', 'INTEGER', false, 11, null);
		$this->addColumn('GRU_FECHA_ACTUALIZACION', 'GruFechaActualizacion', 'TIMESTAMP', false, null, null);
		$this->addColumn('GRU_ELIMINADO', 'GruEliminado', 'SMALLINT', false, 6, null);
		$this->addColumn('GRU_CAUSA_ELIMINACION', 'GruCausaEliminacion', 'VARCHAR', false, 250, null);
		$this->addColumn('GRU_CAUSA_ACTUALIZACION', 'GruCausaActualizacion', 'VARCHAR', false, 250, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // GrupoEquipoTableMap
