<?php


/**
 * This class defines the structure of the 'modelo' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/01/14 20:16:33
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ModeloTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ModeloTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('modelo');
		$this->setPhpName('Modelo');
		$this->setClassname('Modelo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('MOD_CODIGO', 'ModCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('MOD_NOMBRE', 'ModNombre', 'VARCHAR', false, 200, null);
		$this->addColumn('MOD_ELIMINADO', 'ModEliminado', 'SMALLINT', false, 6, null);
		$this->addColumn('MOD_FECHA_REGISTRO_SISTEMA', 'ModFechaRegistroSistema', 'TIMESTAMP', false, null, null);
		$this->addColumn('MOD_USU_CREA', 'ModUsuCrea', 'INTEGER', false, 11, null);
		$this->addColumn('MOD_FECHA_ACTUALIZACION', 'ModFechaActualizacion', 'TIMESTAMP', false, null, null);
		$this->addColumn('MOD_USU_ACTUALIZA', 'ModUsuActualiza', 'INTEGER', false, 11, null);
		$this->addColumn('MOD_CAUSA_ELIMINACION', 'ModCausaEliminacion', 'VARCHAR', false, 250, null);
		$this->addColumn('MOD_CAUSA_ACTUALIZACION', 'ModCausaActualizacion', 'VARCHAR', false, 250, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ModeloTableMap
