<?php


/**
 * This class defines the structure of the 'tamano_particula' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/05/14 16:15:50
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TamanoParticulaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TamanoParticulaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tamano_particula');
		$this->setPhpName('TamanoParticula');
		$this->setClassname('TamanoParticula');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('TAM_CODIGO', 'TamCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('TAM_NOMBRE', 'TamNombre', 'VARCHAR', false, 200, null);
		$this->addColumn('TAM_ELIMINADO', 'TamEliminado', 'SMALLINT', false, 6, null);
		$this->addColumn('TAM_FECHA_REGISTRO_SISTEMA', 'TamFechaRegistroSistema', 'TIMESTAMP', false, null, null);
		$this->addColumn('TAM_USU_CREA', 'TamUsuCrea', 'INTEGER', false, 11, null);
		$this->addColumn('TAM_FECHA_ACTUALIZACION', 'TamFechaActualizacion', 'TIMESTAMP', false, null, null);
		$this->addColumn('TAM_USU_ACTUALIZA', 'TamUsuActualiza', 'INTEGER', false, 11, null);
		$this->addColumn('TAM_CAUSA_ELIMINACION', 'TamCausaEliminacion', 'VARCHAR', false, 250, null);
		$this->addColumn('TAM_CAUSA_ACTUALIZACION', 'TamCausaActualizacion', 'VARCHAR', false, 250, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TamanoParticulaTableMap
