<?php


/**
 * Skeleton subclass for representing a row from the 'fase_ligada' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/28/14 01:28:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FaseLigada extends BaseFaseLigada {

} // FaseLigada
