<?php


/**
 * Skeleton subclass for performing query and update operations on the 'grupo_equipo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/05/14 16:15:44
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class GrupoEquipoPeer extends BaseGrupoEquipoPeer {
    
    public static function listarGruposActivos()
    {
            $fila = 0;
            $datos = array();
            try{
                    $conexion = new Criteria();
                    $conexion->add(GrupoEquipoPeer::GRU_ELIMINADO, false);
                    $grupos = GrupoEquipoPeer::doSelect($conexion);

                    foreach($grupos as $temporal)
                    {
                            $datos[$fila]['gru_codigo'] = $temporal->getGruCodigo();
                            $datos[$fila]['gru_nombre'] = $temporal->getGruNombre();
                            $fila++;
                    }
                    $fila++;
            }
            catch (Exception $excepcion) { }
            return $datos;
    }
} // GrupoEquipoPeer
