<?php


/**
 * Skeleton subclass for representing a row from the 'registro_rep_maquina' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 03/27/14 17:35:50
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RegistroRepMaquina extends BaseRegistroRepMaquina {

} // RegistroRepMaquina
